name: Build and Commit DLL
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./publish
    - name: Commit to another repo
      run: |
        git config --global user.name 'Vignes'
        git config --global user.email 'vignes@live.com.my'
        git clone https://github.com/VedAstro/VedAstro.Python.git
        cp ./publish/*.dll ./other-repo/
        cd other-repo
        git add .
        git commit -m "Add DLL"
        git push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
