name: Auto Update VedAstroDLL To Python Repo
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        #Checks out your code using the actions/checkout@v2 action.
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # This prevents GitHub Actions from using its token
        fetch-depth: 0 # This makes sure all history is fetched
        #Sets up the .NET environment with the specified version using the actions/setup-dotnet@v1 action.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x.x'
        #Restores any dependencies for your project.
    - name: Restore dependencies
      run: dotnet restore ./Library
        #Builds your project in the Release configuration.
    - name: Build
      run: dotnet build ./Library --configuration Release --no-restore
        #Publishes the build output (including the DLL) to the ./publish directory.
    - name: Publish
      run: dotnet publish ./Library --configuration Release --no-build --output ./publish
    - name: Commit to another repo
      run: |
        echo "--------SETTING NAME--------------"
        git config --global user.name 'sengiv'
        git config --global user.email 'vignes@live.com.my'
        # Clones the other repository where you want to commit the DLL.
        echo "--------CLONING VEDASTRO.PYTHON--"
        git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/VedAstro/VedAstro.Python.git
        # Copies the DLL from the ./publish directory to the cloned repository.
        echo "--------COPYING DLL INTO VEDASTRO.PYTHON--"
        cp ./publish/*.dll ./VedAstro.Python/vedastro/dlls
        echo "--------GOING INTO REPO--"
        cd ./VedAstro.Python
        # Commits and pushes the DLL to the other repository.
        echo "--------MAKING A COMMIT--
        git add .
        git commit -m "Auto Update VedAstro.DLL"
        echo "--------MAKING A PUSH FOR IT!--"
        git push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
